/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cg1_20180816;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Random;
/**
 *
 * @author Livnick
 */
public class FrameJogo extends javax.swing.JFrame implements Runnable{

    private boolean left;
    private boolean right;
    private boolean endGame;
    private boolean restartGame;
    /**
     * Creates new form FrameJogo
     */
    public FrameJogo() {
        initComponents();
        createBufferStrategy(2);
        Thread t = new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                left = true;
                break;
            case KeyEvent.VK_RIGHT:
                right = true;
                break;
            case KeyEvent.VK_R:
                restartGame = true;
                break;
            default:
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                left = false;
                break;
            case com.sun.glass.events.KeyEvent.VK_RIGHT:
                right = false;
                break;
            case com.sun.glass.events.KeyEvent.VK_R:
                restartGame = false;
                break;
            default:
                break;
        }
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameJogo().setVisible(true);
            }
        });
    }

    @Override
    public void run() {
        Graphics g;
        
        ArrayList<Base> lista = new ArrayList();
        ArrayList<Base> lixo = new ArrayList();
        
        CarroPlayer player = new CarroPlayer("img/player_resize.png");
        player.setAltura(80);
        player.setLargura(42);
        player.setIncX(0);
        player.setIncY(0);
        player.setY(getHeight() - player.getAltura());
        lista.add(player);
        
        Random r = new Random();
        
        for (int i=0;i<5;i++){
            CarroNPC c;
            if(r.nextBoolean()){
                 c = new CarroNPC("img/npc_resize.png");
                 lista.add(c);
            }else{
                c = new CarroNPC("img/police_resize.png");
                lista.add(c);
            }
        }
        
        while(true){
            
            if(left){
                player.setIncX(-1);
            }else if(right){
                player.setIncX(1);
            }else{
                player.setIncX(0);
            }
            
            g = getBufferStrategy().getDrawGraphics();
            //Clear screen
            g.setColor(Color.GREEN);
            g.fillRect(0, 0, getWidth(), getHeight());
            g.setColor(Color.BLACK);
            g.fillRect(100, 0, getWidth()-200, getHeight());
            g.setColor(Color.YELLOW);
            for(int i=0;i<5;i++){
                g.fillRect(getWidth()/2-5, i*80, 10, 60);
            }
            
            for(Base b : lista){
                if(player.colisao(b)){
                   g.setColor(Color.RED);
                   g.drawString("FIM de JOGO - Tecle R para Reiniciar", 100, 100);
                   endGame = true;
                   b.setIncY(0);
                   b.setY(0);
                }
            }

            for(Base b : lista){
            b.mover();
            }
            
            for(Base b : lista){
                b.desenhar(g);
            }
            

            
            for(Base b: lista){
                Colisao aux = b.trataColisao(getWidth(), getHeight());
                if(aux == Colisao.DOWN){
                    lixo.add(b);
                }
            }
            
            lista.removeAll(lixo);
            for(Base b: lixo){
                b.setY(0);
                b.setIncY(1);
            }
            lista.addAll(lixo);
            
            /*if(endGame && restartGame){
                for (int i=0;i<5;i++){
                    CarroNPC c;
                    if(r.nextBoolean()){
                         c = new CarroNPC("img/npc_resize.png");
                         lista.add(c);
                    }else{
                        c = new CarroNPC("img/police_resize.png");
                        lista.add(c);
                    }
                }
            }*/
            
            
            g.dispose();
            getBufferStrategy().show();
            try {
                Thread.sleep(5);
            } catch (InterruptedException ex) {
            }
            
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
